// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handler

// Error defines model for Error.
type Error struct {
	// Code Error code indicating the type of error.
	Code string `json:"code"`

	// Message Detailed error message.
	Message string `json:"message"`
}

// Message defines model for Message.
type Message struct {
	// Message Message indicating the result of the API call.
	Message string `json:"message"`
}

// Source defines model for Source.
type Source struct {
	// Category Category of the source (e.g., Ecommerce, Dealer, Web).
	Category string `json:"category"`

	// Email Email contact for the source.
	Email string `json:"email"`

	// Name Name of the source (e.g., Tokopedia, Dealer ABC).
	Name string `json:"name"`

	// Secret Password for authenticating the source.
	Secret string `json:"secret"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// SourceId ID of the source.
	SourceId string `json:"sourceId"`

	// SourceSecret Password (secret) associated with the source.
	SourceSecret string `json:"sourceSecret"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken JWT access token.
	AccessToken string `json:"accessToken"`

	// ExpiresIn Expiration time in seconds.
	ExpiresIn float32 `json:"expiresIn"`

	// TokenType Type of the token, typically 'Bearer'.
	TokenType string `json:"tokenType"`
}

// RegisterNewSourceJSONRequestBody defines body for RegisterNewSource for application/json ContentType.
type RegisterNewSourceJSONRequestBody = Source

// TokenGenerationJSONRequestBody defines body for TokenGeneration for application/json ContentType.
type TokenGenerationJSONRequestBody = TokenRequest
