version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped
  app:
    build:
      context: docker/dev
    volumes:
      - ./src:/src
    working_dir: /src
    ports:
      - "127.0.0.1:3000:$PORT"
    environment:
      MYSQL_DSN: "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?parseTime=true"
    env_file:
      - .env
    depends_on:
      - mysql
