// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

// Error defines model for Error.
type Error struct {
	// Code HTTP error code.
	Code string `json:"code"`

	// Message Detailed error message.
	Message string `json:"message"`
}

// InitialTenorLimits List of initial credit limits for different tenor periods.
type InitialTenorLimits = []struct {
	// LimitAmount Maximum credit limit for the given tenor.
	LimitAmount float64 `json:"limitAmount"`

	// MonthRange Duration of the credit limit in months.
	MonthRange int `json:"monthRange"`
}

// Message defines model for Message.
type Message struct {
	// Message Message indicating the result of the API call.
	Message string `json:"message"`
}

// SetInitialCreditLimitJSONRequestBody defines body for SetInitialCreditLimit for application/json ContentType.
type SetInitialCreditLimitJSONRequestBody = InitialTenorLimits
