// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

// Error defines model for Error.
type Error struct {
	// Code Error code indicating the type of error.
	Code string `json:"code"`

	// Message Detailed error message.
	Message string `json:"message"`
}

// Loan defines model for Loan.
type Loan struct {
	// CustomerId Unique ID of the customer applying for the loan.
	CustomerId string `json:"customerId"`

	// ExternalId External reference ID for the loan application.
	ExternalId string `json:"externalId"`

	// Loans List of assets included in the loan application.
	Loans []struct {
		// AmountInterest Interest amount for the asset loan.
		AmountInterest float64 `json:"amountInterest"`

		// AssetName Name of the asset.
		AssetName string `json:"assetName"`

		// ContractNumber Unique contract number for the asset.
		ContractNumber string `json:"contractNumber"`

		// Otr On The Road (OTR) price of the asset.
		Otr float64 `json:"otr"`
	} `json:"loans"`

	// Tenor Loan tenor in months.
	Tenor int `json:"tenor"`
}

// Message defines model for Message.
type Message struct {
	// Message Message indicating the result of the API call.
	Message string `json:"message"`
}

// SubmitLoanJSONRequestBody defines body for SubmitLoan for application/json ContentType.
type SubmitLoanJSONRequestBody = Loan
