// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Customer defines model for Customer.
type Customer struct {
	// DateOfBirth Date of birth of the customer in ISO 8601 format (YYYY-MM-DD).
	DateOfBirth string `json:"dateOfBirth"`

	// FullName Full name of the customer.
	FullName string `json:"fullName"`

	// LegalName The legal name of the customer as per official records.
	LegalName string `json:"legalName"`

	// Nik National Identification Number (NIK) of the customer.
	Nik string `json:"nik"`

	// PlaceOfBirth City or town where the customer was born.
	PlaceOfBirth string `json:"placeOfBirth"`

	// Wage Monthly wage of the customer.
	Wage float64 `json:"wage"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code indicating the type of error.
	Code *string `json:"code,omitempty"`

	// Message Detailed error message.
	Message *string `json:"message,omitempty"`
}

// Message defines model for Message.
type Message struct {
	// Message Message indicating the result of the API call.
	Message string `json:"message"`
}

// RegisterNewCustomerJSONRequestBody defines body for RegisterNewCustomer for application/json ContentType.
type RegisterNewCustomerJSONRequestBody = Customer
